name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm: [server]

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt update
    - run: sudo apt install tox
    - run: tox -e ${{ matrix.charm }}-unit
    - run: tox -e ${{ matrix.charm }}-lint

  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Setup operator environment
      uses: charmed-kubernetes/actions-operator@main
      with:
        provider: microk8s
        channel: 1.21/stable
        charmcraft-channel: latest/candidate

    - name: Enable MetalLB
      run: |
        set -eux
        sg microk8s -c "microk8s enable metallb:10.64.140.43-10.64.140.49"
        sg microk8s -c "microk8s status --wait-ready"

    # ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
    - name: Remove pip-installed virtualenv
      run: |
        set -eux
        sudo pip uninstall -y virtualenv
        sudo apt install -y python3-virtualenv

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install juju-wait --classic
        sudo apt update
        sudo apt install -y firefox-geckodriver tox

    - name: Ensure storage is up
      run: kubectl rollout status deployment/hostpath-provisioner -n kube-system

    - name: Deploy charm dependencies
      timeout-minutes: 15
      run: |
        set -eux
        juju deploy istio --channel 1.11/stable --trust
        juju wait -wvt 600

    - name: Deploy MLflow
      run: |
        set -eux
        sg microk8s -c 'juju bundle deploy --build --destructive-mode'
        juju relate mlflow-server istio-pilot
        juju wait -wvt 900 --retry_errors 20

    - run: tox -e selenium
      env:
        KUBECONFIG: /home/runner/.kube/config

    - run: kubectl get all -A
      if: failure()

    - run: kubectl get virtualservices -A
      if: failure()

    - run: juju status
      if: failure()

    - name: Get mlflow workload logs
      run: kubectl logs --tail 100 -nmlflow -lapp.kubernetes.io/name=mlflow-server
      if: failure()

    - name: Get mlflow operator logs
      run: kubectl logs --tail 100 -nmlflow -loperator.juju.is/name=mlflow-server
      if: failure()

    - name: Generate inspect tarball
      run: >
        sg microk8s <<EOF
          microk8s inspect | \
          grep -Po "Report tarball is at \K.+" | \
          xargs -I {} cp {} inspection-report-${{ strategy.job-index }}.tar.gz
        EOF
      if: failure()

    - name: Upload inspect tarball
      uses: actions/upload-artifact@v2
      with:
        name: inspection-reports
        path: ./inspection-report-${{ strategy.job-index }}.tar.gz
      if: failure()

    - name: Upload selenium screenshots
      uses: actions/upload-artifact@v2
      with:
        name: selenium-screenshots
        path: /tmp/selenium-*.png
      if: failure()

    - name: Upload HAR logs
      uses: actions/upload-artifact@v2
      with:
        name: selenium-har
        path: /tmp/selenium-*.har
      if: failure()
