name: CI

on:
  - push
  - pull_request

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm: [server]

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt update
    - run: sudo apt install tox
    - run: tox -e ${{ matrix.charm }}

  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Setup operator environment
      uses: charmed-kubernetes/actions-operator@main
      with:
        provider: microk8s
        charmcraft-channel: latest/candidate

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install juju-wait --classic
        sudo apt update
        sudo apt install -y firefox-geckodriver tox

    - name: Ensure storage is up
      run: kubectl rollout status deployment/hostpath-provisioner -n kube-system

    - run: sg microk8s -c 'juju bootstrap microk8s uk8s'
    - run: juju add-model mlflow

    - name: Deploy charm dependencies
      run: |
        set -eux
        juju deploy istio --trust
        juju config istio-pilot default-gateways=kubeflow-gateway
        juju wait -wvt 300

    - name: Deploy MLflow
      run: |
        set -eux
        juju bundle deploy --build
        juju relate mlflow-server istio-pilot
        juju wait -wvt 300

    - run: tox -e selenium

    - run: kubectl get all -A
      if: failure()

    - run: kubectl get virtualservices -A
      if: failure()

    - run: juju status
      if: failure()

    - run: kubectl logs --tail 100 -nmlflow -lapp.kubernetes.io/name=mlflow-server
      if: failure()

    - run: kubectl logs --tail 100 -nmlflow -loperator.juju.is/name=mlflow-server
      if: failure()

    - name: Generate inspect tarball
      run: >
        sg microk8s <<EOF
          microk8s inspect | \
          grep -Po "Report tarball is at \K.+" | \
          xargs -I {} cp {} inspection-report-${{ strategy.job-index }}.tar.gz
        EOF
      if: failure()

    - name: Upload inspect tarball
      uses: actions/upload-artifact@v2
      with:
        name: inspection-reports
        path: ./inspection-report-${{ strategy.job-index }}.tar.gz
      if: failure()

    - name: Upload selenium screenshots
      uses: actions/upload-artifact@v2
      with:
        name: selenium-screenshots
        path: /tmp/selenium-*.png
      if: failure()

    - name: Upload HAR logs
      uses: actions/upload-artifact@v2
      with:
        name: selenium-har
        path: /tmp/selenium-*.har
      if: failure()
